[WAIT 1000],
[SYSTEM RUN],
[WAIT 3000],
::gedit::300
::[ENTER],
[WAIT 1000],
::hola mundo.::300
::RUN
[WAIT 5000],

Academic Free License ("AFL") v. 3.0

This Academic Free License (the "License") applies to any original work of authorship (the "Original Work") whose owner (the "Licensor") has placed the following licensing notice adjacent to the copyright notice for the Original Work:

Licensed under the Academic Free License version 3.0

   1. Grant of Copyright License. Licensor grants You a worldwide::300,[ENTER/], royalty-free::300,[ENTER/], non-exclusive::300,[ENTER/], sublicensable license::300,[ENTER/], for the duration of the copyright::300,[ENTER/], to do the following::300

         1. to reproduce the Original Work in copies::300,[ENTER/], either alone or as part of a collective work;::300

         2. to translate::300,[ENTER/], adapt::300,[ENTER/], alter::300,[ENTER/], transform::300,[ENTER/], modify::300,[ENTER/], or arrange the Original Work::300,[ENTER/], thereby creating derivative works ("Derivative Works") based upon the Original Work;::300

         3. to distribute or communicate copies of the Original Work and Derivative Works to the public::300,[ENTER/], under any license of your choice that does not contradict the terms and conditions::300,[ENTER/], including Licensor's reserved rights and remedies::300,[ENTER/], in this Academic Free License;::300

         4. to perform the Original Work publicly; and::300

         5. to display the Original Work publicly.::300

   2. Grant of Patent License. Licensor grants You a worldwide::300,[ENTER/], royalty-free::300,[ENTER/], non-exclusive::300,[ENTER/], sublicensable license::300,[ENTER/], under patent claims owned or controlled by the Licensor that are embodied in the Original Work as furnished by the Licensor::300,[ENTER/], for the duration of the patents::300,[ENTER/], to make::300,[ENTER/], use::300,[ENTER/], sell::300,[ENTER/], offer for sale::300,[ENTER/], have made::300,[ENTER/], and import the Original Work and Derivative Works.::300

   3. Grant of Source Code License. The term "Source Code" means the preferred form of the Original Work for making modifications to it and all available documentation describing how to modify the Original Work. Licensor agrees to provide a machine-readable copy of the Source Code of the Original Work along with each copy of the Original Work that Licensor distributes. Licensor reserves the right to satisfy this obligation by placing a machine-readable copy of the Source Code in an information repository reasonably calculated to permit inexpensive and convenient access by You for as long as Licensor continues to distribute the Original Work.::300

   4. Exclusions From License Grant. Neither the names of Licensor::300,[ENTER/], nor the names of any contributors to the Original Work::300,[ENTER/], nor any of their trademarks or service marks::300,[ENTER/], may be used to endorse or promote products derived from this Original Work without express prior permission of the Licensor. Except as expressly stated herein::300,[ENTER/], nothing in this License grants any license to Licensor's trademarks::300,[ENTER/], copyrights::300,[ENTER/], patents::300,[ENTER/], trade secrets or any other intellectual property. No patent license is granted to make::300,[ENTER/], use::300,[ENTER/], sell::300,[ENTER/], offer for sale::300,[ENTER/], have made::300,[ENTER/], or import embodiments of any patent claims other than the licensed claims defined in Section 2. No license is granted to the trademarks of Licensor even if such marks are included in the Original Work. Nothing in this License shall be interpreted to prohibit Licensor from licensing under terms different from this License any Original Work that Licensor otherwise would have a right to license.::300

   5. External Deployment. The term "External Deployment" means the use::300,[ENTER/], distribution::300,[ENTER/], or communication of the Original Work or Derivative Works in any way such that the Original Work or Derivative Works may be used by anyone other than You::300,[ENTER/], whether those works are distributed or communicated to those persons or made available as an application intended for use over a network. As an express condition for the grants of license hereunder::300,[ENTER/], You must treat any External Deployment by You of the Original Work or a Derivative Work as a distribution under section 1(c).::300

   6. Attribution Rights. You must retain::300,[ENTER/], in the Source Code of any Derivative Works that You create::300,[ENTER/], all copyright::300,[ENTER/], patent::300,[ENTER/], or trademark notices from the Source Code of the Original Work::300,[ENTER/], as well as any notices of licensing and any descriptive text identified therein as an "Attribution Notice." You must cause the Source Code for any Derivative Works that You create to carry a prominent Attribution Notice reasonably calculated to inform recipients that You have modified the Original Work.::300

   7. Warranty of Provenance and Disclaimer of Warranty. Licensor warrants that the copyright in and to the Original Work and the patent rights granted herein by Licensor are owned by the Licensor or are sublicensed to You under the terms of this License with the permission of the contributor(s) of those copyrights and patent rights. Except as expressly stated in the immediately preceding sentence::300,[ENTER/], the Original Work is provided under this License on an "AS IS" BASIS and WITHOUT WARRANTY::300,[ENTER/], either express or implied::300,[ENTER/], including::300,[ENTER/], without limitation::300,[ENTER/], the warranties of non-infringement::300,[ENTER/], merchantability or fitness for a particular purpose. THE ENTIRE RISK AS TO THE QUALITY OF THE ORIGINAL WORK IS WITH YOU. This DISCLAIMER OF WARRANTY constitutes an essential part of this License. No license to the Original Work is granted by this License except under this disclaimer.::300

   8. Limitation of Liability. Under no circumstances and under no legal theory::300,[ENTER/], whether in tort (including negligence)::300,[ENTER/], contract::300,[ENTER/], or otherwise::300,[ENTER/], shall the Licensor be liable to anyone for any indirect::300,[ENTER/], special::300,[ENTER/], incidental::300,[ENTER/], or consequential damages of any character arising as a result of this License or the use of the Original Work including::300,[ENTER/], without limitation::300,[ENTER/], damages for loss of goodwill::300,[ENTER/], work stoppage::300,[ENTER/], computer failure or malfunction::300,[ENTER/], or any and all other commercial damages or losses. This limitation of liability shall not apply to the extent applicable law prohibits such limitation.::300

   9. Acceptance and Termination. If::300,[ENTER/], at any time::300,[ENTER/], You expressly assented to this License::300,[ENTER/], that assent indicates your clear and irrevocable acceptance of this License and all of its terms and conditions. If You distribute or communicate copies of the Original Work or a Derivative Work::300,[ENTER/], You must make a reasonable effort under the circumstances to obtain the express assent of recipients to the terms of this License. This License conditions your rights to undertake the activities listed in Section 1::300,[ENTER/], including your right to create Derivative Works based upon the Original Work::300,[ENTER/], and doing so without honoring these terms and conditions is prohibited by copyright law and international treaty. Nothing in this License is intended to affect copyright exceptions and limitations (including "fair use" or "fair dealing"). This License shall terminate immediately and You may no longer exercise any of the rights granted to You by this License upon your failure to honor the conditions in Section 1(c).::300

  10. Termination for Patent Action. This License shall terminate automatically and You may no longer exercise any of the rights granted to You by this License as of the date You commence an action::300,[ENTER/], including a cross-claim or counterclaim::300,[ENTER/], against Licensor or any licensee alleging that the Original Work infringes a patent. This termination provision shall not apply for an action alleging patent infringement by combinations of the Original Work with other software or hardware.::300

  11. Jurisdiction::300,[ENTER/], Venue and Governing Law. Any action or suit relating to this License may be brought only in the courts of a jurisdiction wherein the Licensor resides or in which Licensor conducts its primary business::300,[ENTER/], and under the laws of that jurisdiction excluding its conflict-of-law provisions. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. Any use of the Original Work outside the scope of this License or after its termination shall be subject to the requirements and penalties of copyright or patent law in the appropriate jurisdiction. This section shall survive the termination of this License.::300

  12. Attorneys' Fees. In any action to enforce the terms of this License or seeking damages relating thereto::300,[ENTER/], the prevailing party shall be entitled to recover its costs and expenses::300,[ENTER/], including::300,[ENTER/], without limitation::300,[ENTER/], reasonable attorneys' fees and costs incurred in connection with such action::300,[ENTER/], including any appeal of such action. This section shall survive the termination of this License.::300

  13. Miscellaneous. If any provision of this License is held to be unenforceable::300,[ENTER/], such provision shall be reformed only to the extent necessary to make it enforceable.::300

  14. Definition of "You" in This License. "You" throughout this License::300,[ENTER/], whether in upper or lower case::300,[ENTER/], means an individual or a legal entity exercising rights under::300,[ENTER/], and complying with all of the terms of::300,[ENTER/], this License. For legal entities::300,[ENTER/], "You" includes any entity that controls::300,[ENTER/], is controlled by::300,[ENTER/], or is under common control with you. For purposes of this definition::300,[ENTER/], "control" means (i) the power::300,[ENTER/], direct or indirect::300,[ENTER/], to cause the direction or management of such entity::300,[ENTER/], whether by contract or otherwise::300,[ENTER/], or (ii) ownership of fifty percent (50%) or more of the outstanding shares::300,[ENTER/], or (iii) beneficial ownership of such entity.::300

  15. Right to Use. You may use the Original Work in all ways not otherwise restricted or conditioned by this License or by law::300,[ENTER/], and Licensor promises not to interfere with or be responsible for such uses by You.::300

  16. Modification of This License. This License is Copyright © 2005 Lawrence Rosen. Permission is granted to copy::300,[ENTER/], distribute::300,[ENTER/], or communicate this License without modification. Nothing in this License permits You to modify this License as applied to the Original Work or to Derivative Works. However::300,[ENTER/], You may modify the text of this License and copy::300,[ENTER/], distribute or communicate your modified version (the "Modified License") and apply it to other original works of authorship subject to the following conditions: (i) You may not indicate in any way that your Modified License is the "Academic Free License" or "AFL" and you may not use those names in the name of your Modified License; (ii) You must replace the notice specified in the first paragraph above with the notice "Licensed under <insert your license name here>" or with a notice of your own that is not confusingly similar to the notice in this License; and (iii) You may not claim that your original works are open source software unless your Modified License has been approved by Open Source Initiative (OSI) and You comply with its license review and certification process.::300

::RUN